objects/CIO__c.object
<CustomObject>
    <fields>
        <fullName>DataContent__c</fullName>
        <label>DataContent</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Drinker__c</fullName>
        <label>Drinker</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Somker__c</fullName>
        <label>Somker</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CIO</label>
    <nameField>
        <label>Sample Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestPageController.cls
public class TestPageController {

    public CIO__c cData {get;set;}
    public TestPageController(){
        String accID = ApexPages.currentPage().getParameters().get('Id');
        
        if(accID != null)
        {
            cData = [SELECT Id,Name,DataContent__c,Somker__c,Drinker__c FROM CIO__c WHERE Id =: accID];
        }
        else {cData = new CIO__c();}  
    }
    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Yes','Yes'));
        options.add(new SelectOption('No','No')); 
        return options;
    }
    public Pagereference showLSDesc(){
        return null;
    }
    
}